MyApps/MyApps/urls.py
from django.contrib import admin
from django.urls import path, include
# fill out paths for apps urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('weather/', include('weather.urls')),
    path('toDoSticker/', include('toDoSticker.urls')),
    path('cv/', include('cv.urls'))
]

MyApps/cv/urls.py
from django.urls import path

from . import views
# weather appname and urls
app_name='cv'
urlpatterns = [
    path('', views.index, name='index'),
    path('newCV/', views.newCV, name='newCV'),
    path('viewCVs/', views.viewCVs, name='viewCVs'),
    path('newCV/addCV/', views.addCV, name='addCV'),
    path('viewCVs/deleteCV/<int:cv_id>/', views.deleteCV, name='deleteCV'),
    path('viewCVs/printCV/<int:cv_id>/', views.printCV, name='printCV'),
]

MyApps/pages/urls.py
from django.urls import path

from . import views
#'pages' urls
urlpatterns = [
    path('', views.index, name='index'),
]

MyApps/toDoSticker/urls.py
from django.urls import path

from . import views
#to Do app_name and urls
app_name='To_Do_stickers'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
]

MyApps/weather/urls.py
from django.urls import path

from . import views
# weather appname and urls
app_name='weather'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.addCity, name='addCity'),
    path('delete/<int:city_id>', views.deleteCity, name='delCity'),
]

MyApps/cv/models.py
from django.db import models

# Create your models here.
class cvModel(models.Model):
    fname = models.CharField(max_length=30)
    sname = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    education = models.CharField(max_length=20)
    languages = models.CharField(max_length=30)
    details = models.CharField(max_length=100)
    def __str__(self):
        return self.fname + ' ' + self.sname + ' ' + self.phone + ' ' + self.education + ' ' + self.languages + ' ' + self.details

MyApps/pages/models.py
from django.db import models

# Create your models here.

MyApps/toDoSticker/models.py
from django.db import models
from datetime import datetime
# Create your models here.
# The todolistitems consists of a char var (listItem) and a time object (time_limit)
class toDoListItems(models.Model):
    listItem = models.CharField(max_length=30)
    time_limit = models.TimeField('Until when')
    def __str__(self):
        return self.listItem + ' ' + self.time_limit.strftime('%H:%M')

MyApps/weather/models.py
from django.db import models

# Create your models here.
# weather model is just the city name
class savedLocations(models.Model):
    location = models.CharField(max_length=100)
    def __str__(self):
        return self.location

MyApps/cv/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, FileResponse
from .models import cvModel
from django.db import connections
import io
from fpdf import FPDF
# Create your views here.
def index(request):
    return render(request, 'cv/index.html')

def addCV(request):
    fname = request.POST.get('fname')
    sname = request.POST.get('sname')
    phone = request.POST.get('phone')
    edu = request.POST.get('edu')
    languages = ""
    eng = request.POST.get('eng')
    if eng is not None : languages+=eng
    jap = request.POST.get('jap')
    if jap is not None: languages += jap
    gre = request.POST.get('gre')
    if gre is not None: languages += gre
    desc = request.POST.get('desc')
    new_item = cvModel(fname=fname, sname=sname, phone=phone, education=edu, languages=languages, details=desc)
    new_item.save()
    return HttpResponseRedirect('../../')

def newCV(request):
    return render(request, 'cv/newCV.html')

def viewCVs(request):
    cvs = cvModel.objects.all()
    cv_list = []
    for cv in cvs:
        cv_in_list = str(cv).split(' ')
        fname=cv_in_list[0]
        sname=cv_in_list[1]
        phone=cv_in_list[2]
        edu=cv_in_list[3]
        lang=cv_in_list[4]
        det = ' '.join(cv_in_list[5:])
        cv_list.append({'id': cv.id, 'fname':fname, 'sname':sname, 'phone':phone, 'edu':edu, 'lang':lang, 'det':det})
    return render(request, 'cv/viewCVs.html', {'cv_list': cv_list})

#get the city id and delete from saved locations
def deleteCV(request, cv_id):
    delCV = cvModel.objects.get(pk=cv_id)
    delCV.delete()
    return HttpResponseRedirect('../../')

def printCV(request, cv_id):
    cv = cvModel.objects.get(pk=cv_id)
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=15)
    pdf.cell(200, 10, txt="MY CV",ln=1)
    pdf.cell(200, 10, txt="name:{}".format(cv.fname), ln=2)
    pdf.cell(200, 10, txt="surname:{}".format(cv.sname),ln=3)
    pdf.cell(200, 10, txt="phone:{}".format(cv.phone),ln=4)
    pdf.cell(200, 10, txt="education:{}".format(cv.education),ln=5)
    pdf.cell(200, 10, txt="languages:{}".format(cv.languages),ln=6)
    pdf.cell(200, 10, txt="description:{}".format(cv.details),ln=7)
    pdf.output("myCV.pdf")
    return HttpResponseRedirect('../../')

MyApps/pages/views.py
from django.shortcuts import render

# Create your views here.
#render main page
def index(request):
    return render(request, 'pages/index.html')

MyApps/toDoSticker/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.
from .models import toDoListItems

# Create your views here.
def index(request):
    # query for tasks and sending it to html index
    to_do_list = toDoListItems.objects.all()
    return render(request, 'toDoSticker/index.html', {'to_do_list': to_do_list})

# for deletion
def delete(request, id):
    item_to_delete = toDoListItems.objects.get(pk=id)
    item_to_delete.delete()
    return HttpResponseRedirect('../../')

# for adding a new item get from POST the [task, time]
# and add them to the database. then redirect to index
def add(request):
    task = request.POST.get('task')
    time = request.POST.get('time')
    new_item = toDoListItems(listItem=task, time_limit=time)
    new_item.save()
    return HttpResponseRedirect('../')

MyApps/weather/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import requests
from .models import savedLocations
# Create your views here.
def index(request):
    #for every saved location find weather info
    locs = savedLocations.objects.all()
    locations = []
    for loc in locs:
        locations.append(getWeather(loc))
    return render(request, 'weather/index.html', {'locations' : locations })

def getWeather(city):
    #build the url
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&appid=c21807537671ed836a423612bca624e8'.format(city)
    #query result
    query = requests.get(url).json()
    #get the city_name, city_temp, temp description and then icon name pair for weather description
    city_name = query['name']
    city_temp = int(query['main']['temp'] - 273.15)
    city_temp_desc = query['weather'][0]['description']
    city_temp_icon = query['weather'][0]['icon']
    return {'id': city.id, 'city': city_name, 'temp': city_temp, 'desc': city_temp_desc, 'icon': city_temp_icon}

def addCity(request):
    #add a city
    city = request.POST.get('city')
    #create the object and try to get weather info
    new_item = savedLocations(location=city)
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&appid=c21807537671ed836a423612bca624e8'.format(city)
    query = requests.get(url).json()
    #if query returns message then an error occured
    if('message' in query.keys() and query['message'] == 'city not found'):
        error_message = 'city not found'
        return HttpResponseRedirect('../', {'error_message': error_message })
    #else everything is ok. Location is saved and return to index
    else:
        new_item.save()
        return HttpResponseRedirect('../')

#get the city id and delete from saved locations
def deleteCity(request, city_id):
    delCity = savedLocations.objects.get(pk=city_id)
    delCity.delete()
    return HttpResponseRedirect('../')

MyApps/templates/base.html
<!--BASE HTML FILE. EACH APP EXTENDS THIS-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}My Apps {% endblock %}</title>
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

MyApps/templates/cv/index.html
{% extends 'base.html' %}
{% block content %}
<!--Two buttons for app entry-->
    <div class="card text-center">
        <div class="card-body">
            <h1>CVs App</h1>
            <a class="btn btn-dark" href="{% url 'cv:viewCVs' %}">View CVs</a>
            <a class="btn btn-dark" href="{%url 'cv:newCV' %}"> Create CV</a>
            <a class="btn btn-dark" href="{% url 'index' %}">
                Back to My Apps
            </a>
        </div>
    </div>
{% endblock %}

MyApps/templates/cv/newCV.html
{% extends 'base.html' %}
{% block content %}
<!--Two buttons for app entry-->
    <div class="card text-center">
        <div class="card-body">
            <h1>Create CV</h1>
            <form action="addCV/" method="POST">
                {% csrf_token %}
                <label for="fname">First Name</label>
                <input type="text" name="fname">
                <br>
                <label for="sname">SurName</label>
                <input type="text" name="sname">
                <br>
                <label for="phone">Phone Number</label>
                <input type="number" name="phone">
                <br>
                <label for="edu">Education</label>
                <select name="edu">
                    <option value="High School">High School</option>
                    <option value="Graduate">Graduate</option>
                    <option value="Post Graduate">Post Graduate</option>
                </select>
                <br>
                <h4>Languages</h4>
                <input type="checkbox" id="eng" name="eng" value="English">
                <label for="eng">English</label><br>
                <input type="checkbox" id="jap" name="jap" value="Japanese">
                <label for="eng">Japanese</label><br>
                <input type="checkbox" id="gre" name="gre" value="Greek">
                <label for="eng">Greek</label><br>
                <h4>Details</h4>
                <textarea name="desc" value="{{text}}"></textarea>
                <br>
                <input type="submit" name="submit" value="Submit">


            </form>
            <a class="btn btn-dark" href="{% url 'cv:index' %}">
                Back
            </a>
        </div>
    </div>
{% endblock %}

MyApps/templates/cv/viewCVs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    ALL CVS
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% if cv_list %}
                        {% for cv in cv_list %}
                            <div class="box">
                                <article class="media">
                                    <div class="media-left">

                                    </div>
                                    <div class="media-content">
                                        <div class="content">
                                            <p>
                                                <span class="title">{{ cv.fname }} {{cv.sname}}</span>
                                                <br>
                                            </p>
                                            <p>
                                                <span class="subtitle">{{ cv.phone }}</span>
                                                <br>
                                                <span class="subtitle">{{ cv.edu }}</span>
                                                <br>
                                                <span class="subtitle">{{ cv.lang }}</span>
                                                <br>
                                                <span class="subtitle">{{ cv.det }}</span>
                                                <br>
                                            </p>
                                        </div>
                                    </div>
                                </article>
<!-- We can also delete saved locations                               -->
                                <form action="deleteCV/{{cv.id}}/" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" name="submit" value="delete">
                                </form>
                                 <form action="printCV/{{cv.id}}/" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" name="print" value="print">
                                </form>
                            </div>
                        {% endfor %}
<!-- If database empty                    -->
                    {% else %}
                    <h2>Please add a CV ! </h2>
                    {% endif %}
                    <a class="btn btn-dark" href="{% url 'cv:index' %}">Back</a>
                    <a class="btn btn-dark" href="{% url 'cv:newCV' %}">Create CV</a>
                </div>

            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>
</html>

MyApps/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
<!--Two buttons for app entry-->
    <div class="card text-center">
        <div class="card-body">
            <h1>Welcome to MyApps</h1>
            <a class="btn btn-dark" href="{% url 'To_Do_stickers:index' %}">
                To Do Stickers
            </a>
            <a class="btn btn-dark" href="{% url 'weather:index' %}">
                What's the weather today ?
            </a>
            <a class="btn btn-dark" href="{% url 'cv:index' %}">
                Create CV ?
            </a>
        </div>
    </div>
{% endblock %}

MyApps/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">My Apps</a>
    </div>
</nav>

MyApps/templates/toDoSticker/index.html
{% extends 'base.html' %}
<!--implement block content-->
{% block content %}

    <div class="card text-center">
        <div class="card-body">
            <h1>TO DO REMINDERS</h1>
<!--if to list exists -->
            {% if to_do_list %}
            <h1>Tasks for the day</h1>
<!--print everyitem while specifing deleted button for specific task-->
            {% for task in to_do_list %}
            <form action="delete/{{task.id}}/" method="POST">
                {% csrf_token %}
                <li>{{task.listItem}} {{task.time_limit}} <input type="submit" name="choice" value="Done!"></li>
            </form>
            {% endfor %}
        <br>
<!-- If tasks are done, relax-->
    {% else %}
    <h1>No more tasks. Relax !</h1>
    {% endif %}
<!-- For adding new task write its name and specify the deadline -->
            <form action="add/" method="POST">
                {% csrf_token %}
                <input type="text" placeholder="Task" name="task" required>
                <input type="time" name="time" >
                <input type="submit" value="New task">
            </form>
            <br>
            <a class="btn btn-dark" href="{% url 'index' %}">
                Back to My Apps
            </a>
        </div>
    </div>
{% endblock %}

MyApps/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
<!--  WEATHER SEARCH   -->
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form action="add/" method="POST">

                        <div class="field has-addons">
<!-- complete the form to add a new location (if it exists)-->
                            <div class="control is-expanded">
                                {% csrf_token %}
                                <input class="input" type="text" name='city' value="{{city}}" placeholder="City Name" required>
                            </div>
                            <div class="control">
                                <input type="submit" class="button is-info" value="Add City"/>
                            </div>
                        </div>
                        <h2>{{error_message}}</h2>

                    </form>
                    <br>
                    <a class="btn btn-dark" href="{% url 'index' %}">Back to My Apps</a>
                </div>
            </div>
        </div>
    </section>
<!--    WEATHER ICON -->
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
<!--    If locations exist in database -->
                    {% if locations %}
<!--    For every location   render info-->
                        {% for location in locations %}
                            <div class="box">
                                <article class="media">
                                    <div class="media-left">
                                        <figure class="image is-50x50">
<!--    Weather icon name is given from query                                            -->
                                            <img src="http://openweathermap.org/img/w/{{location.icon}}.png" alt="Image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <div class="content">
                                            <p>
<!--   With cityname,citytemp and weather desc                                              -->
                                                <span class="title">{{ location.city }}</span>
                                                <br>
                                                <span class="subtitle">{{ location.temp }}°C</span>
                                                <br> {{ location.desc }}
                                            </p>
                                        </div>
                                    </div>
                                </article>
<!-- We can also delete saved locations                               -->
                                <form action="delete/{{location.id}}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" name="submit" value="delete">
                                </form>
                            </div>
                        {% endfor %}
<!-- If database empty                    -->
                    {% else %}
                    <h2>Please add a location ! </h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>
</html>